- include: check_vars.yml tags=percona
- include: percona.yml tags=percona,percona:install
# - include: percona-client.yml tags=percona,percona:client

# mysql_replication is badly broken
# it is ok on a NEW server, but fails miserably on a running server
# don't expect it to handle a proper binlog or logpos
#- include: slave.yml tags=percona,percona:client,percona:slaves
#  when: "percona_master_host and '{{percona_slaves_group}}' in group_names"

- include: backup.yml tags=backup,percona
  when: percona_backup

- include: datadog.yml tags=percona,datadog
  when: percona_datadog_user and percona_datadog_password and datadog_enabled
