---
- import_tasks: check_vars.yml
  tags:
    - percona
    - check

- import_tasks: percona.yml
  tags:
    - percona
    - percona:install

# mysql_replication won't help you with replication
# it is ok on a NEW server, but fails miserably on a running server
# don't expect it to handle a proper binlog or logpos
# so in the slave.yml tasks, all calls to mysql_replication have been removed
- import_tasks: slave.yml
  when: percona_master_host is defined and percona_master_host and percona_slaves_group in group_names
  tags:
    - percona
    - percona:client
    - percona:slaves

- import_tasks: backup.yml
  when: percona_backup
  tags:
    - percona
    - backup
    - percona:backup

- import_tasks: monitoring.yml
  when: percona_monitoring_user is defined and percona_monitoring_user
  tags:
    - percona
    - monitoring
