---
# Percona Slaves Setup
# We assume that, if a master slace setup is user, we bind to a specific interface

- name: Sets percona master IP
  set_fact:
    __percona_master_ip: "{{ hostvars[percona_master_host]['ansible_' + percona_bind_interface]['ipv4']['address'] }}"

- name: Adds required replication users
  mysql_user:
    login_user: root
    login_password: "{{ percona_root_password }}"
    name: "{{ percona_replication_user }}"
    password: "{{ percona_replication_password }}"
    priv: "*.*:REPLICATION SLAVE"
    host: "{{ hostvars[item]['ansible_' + percona_bind_interface]['ipv4']['address'] }}"
  with_items:
    - "{{ groups[percona_slaves_group] }}"
  delegate_to: "{{ percona_master_host }}"
